# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e260d478d3517d2a1f1f7f9cdc50b0f80f231b536272109c08c399a46e71ab78d215a2073fa471b211ac255f06ceacdab429497a04b862e300e9fe8b969a66e

test:
  secret_key_base: ac3c7b06ede2bc25ad5965548f2ea1503477cee7c89bd94607c5ab9d93a1589febe3fbdac2624c46bf23af3fb66ca54cfee05c16565767079584aea7c23c94c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
